apiVersion: v1
kind: Pod
metadata:
  name: mongodb-shell
  namespace: skander-pfe
  labels:
    app: mongodb-shell
spec:
  containers:
  - name: mongodb-shell
    image: mongo:4.4
    command: ['sleep', 'infinity']