apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: skander-pfe
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32520
  type: NodePort