---
- name: Deploy Back App on K8S
  hosts: masters
  become: yes
  tasks:

  #Delete Old Deployment and Service of back
    - name: Delete old Deployment of Backend NodeJS from K8S
      command: kubectl delete -n iheb deployment node-app-deployment
      become: yes
      become_user: ubuntu

    - name: Delete old Service of Backend Nodejs On K8S
      command: kubectl delete -n iheb service node-app-service
      become: yes
      become_user: ubuntu

#Create new Deployment and Service for back
    - name: Create new Deployment for Project Node On K8S
      command: kubectl apply -f /home/ubuntu/kubernetes-app/Deployment_app.yaml
      become: yes
      become_user: ubuntu

    - name: Create new Service for Project Node On K8S
      command: kubectl apply -f /home/ubuntu/kubernetes-app/Service_app.yaml
      become: yes
      become_user: ubuntu